### ISSUE TITLE
Feature request: dashed lines

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.flot#26]
I want to display different values of different rooms in one chart (e.g. temperature and humidity for room 1 and room 2).
I would like to give each room its own color, e.g. Room 1 = red, Room 2 = green.
To display the lines of temperature and humidity differently I would like to make e.g. temperature a sold line and humidity a dashed or dotted line.

Dashed lines are supported in flot via a plugin:
https://github.com/cquartier/flot.dashes

**Comment by GermanBluefox** [comment]
As far as I know, flot does not support dashes or dotted line.

вт, 22 мая 2018 г., 9:36 mswiege <notifications@github.com>:

**Comment by Hypnos3** [comment]
If I read the request correctly, the whish is to integrate the plugin https://github.com/cquartier/flot.dashes in **ioBroker.flot**.

**Comment by mswiege** [comment]
Exactly :-)

**Comment by GermanBluefox** [comment]
Done with https://github.com/ioBroker/ioBroker.flot/commit/a190d657df7df4211c45c55590a3506a611b945a

**Comment by mswiege** [comment]
Awesome. But sadly I wasn't able to get it to work. I updated to version 1.9.0 (adapter shows that version but flot's edit screen still shows 1.7.0 but I assume that is just a bug, right?).
As in the editor I couldn't see the dashes option in the line settings I manually added the parameter to the IFrame (url encoded of course): &l[0][dashes]=true
But this still shows a solid line. Any ideas?

**Comment by B4n4n3** [comment]
Dashed lines can not turned off by clicking on the legend.
